ecommerce/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("register/", views.UserRegistrationView.as_view(), name="user_register"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

ecommerce/home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

ecommerce/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .managers import UserManager 



class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=11, unique=True) 
    full_name = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "phone_number"
    REQUIRED_FIELDS = ["full_name", "email"]

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return True
    
    def has_module_perms(self, app_label):
        return True
    
    @property
    def is_staff(self):
        return self.is_admin
    

ecommerce/home/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to="products/")
    avalable = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return f"{self.name} - {self.price}"

ecommerce/accounts/forms.py
from typing import Any
from django import forms
from .models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label="password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="confirm password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("email", "phone_number", "full_name")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password1"] and cd["password2"] and cd["password1"] != cd["password2"]:
            raise forms.ValidationError("passwords do not match")
        return cd["password2"]
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(help_text="you can change password using <a href=\"../password\">this link</a>.")

    class Meta:
        model = User
        fields = ("email", "phone_number", "full_name", "password", "last_login")

class UserRegistrationForm(forms.Form):
    email = forms.EmailField()
    phone_number = forms.CharField(max_length=11)
    full_name = forms.CharField(max_length=50)
    password = forms.CharField(label="password", widget=forms.PasswordInput())

    def clean_email(self):
        email = self.cleaned_data["email"]
        user = User.objects.filter(email=email).exists()
        if user:
            raise forms.ValidationError("email already exist")
        return email

    def clean_phone_number(self):
        phone_number = self.cleaned_data["phone_number"]
        user = User.objects.filter(phone_number=phone_number).exists()
        if user:
            raise forms.ValidationError("phone_number already exist")
        return phone_number


    

    

ecommerce/accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserRegistrationForm
from .models import User
from django.contrib import messages


class UserRegistrationView(View):
    form_class = UserRegistrationForm

    def get(self, request):
        form = self.form_class
        return render(request, 'accounts/register.html', {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(email=cd["email"], phone_number=cd["phone_number"], full_name=cd["full_name"], password=cd["password"])
            messages.success(request, "You Are Registered  Successfully", extra_tags="success")
            return redirect("home:home")
        return render(request, 'accounts/register.html', {'form': form})

ecommerce/home/views.py
from django.shortcuts import render
from django.views import View


class HomeView(View):
    def get(self, request):
        return render(request, "home/home.html")

ecommerce/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %} Registraion {% endblock %}

{% block content %}

    <form action="" method="post">

        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register">

    </form>

{% endblock %}

ecommerce/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}


{% block extra_headers %}

    <link rel="stylesheet" href="{% static 'home/css/home_style.css' %}">
    
{% endblock %}


{% block content %}

    <h1>
        Home Page...
    </h1>

{% endblock %}

ecommerce/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {%block title%}  {% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
    {% block extra_headers %}  {% endblock %}
</head>
<body>

    {% include 'inc/navbar.html' %}
    
    <div class="jumbotron">

        {% include 'inc/messages.html' %}
        {% block content %}  {% endblock %}

    </div>
    
</body>
</html>

ecommerce/templates/inc/messages.html
{% if messages %}

    {% for msg in messages %}

        <p class="alert alert-{{msg.tags}}"> {{msg}} </p>

    {% endfor %}

{% endif %}

ecommerce/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Asama</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_register' %}">Register</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>